### ISSUE TITLE
Support espressif/ESP8266_NONOS_SDK

### ISSUE THREAD

**Issue by Evgsurf** [QB4-dev/esp_nano_httpd#1]
Hello. 
Is it comportable with espressif/ESP8266_NONOS_SDK or it will work only with pfalcon/esp-open-sdk ?

Best Regards
Evgeny

**Comment by QB4-dev** [comment]
Sorry for late answer.

Yes it is compatible with Espressifs NONOS SDK.
I made test project to work with new SDK:
https://github.com/QB4-dev/esp_nano_httpd_basic_example/tree/espressif-NONOSDK-test

esp_nano_httpd works without changes, but with new SDK you need declare partition table before user_init function
